version: 2.1
jobs:
    test:
        docker:
            - image: circleci/node:12.13
        steps:
            - checkout
            - run: npm install
            - run: npm run test -- --coverage
